FROM python:3.11-slim-bookworm

WORKDIR /app
RUN apt-get update -o Acquire::Retries=5 \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*
COPY pyproject.toml /app/pyproject.toml
COPY app /app/app
RUN pip install --no-cache-dir -e .
CMD ["rq", "worker", "video:normal", "image:normal", "tool:normal", "--url", "redis://redis:6379/0"]
